demo_index:
    path: /demo
    controller: App\Controller\TweetController::demo

demo_tweet:
    path: /demoTweet
    controller: App\Controller\TweetController::demoTweet

index:
    path: /
    controller: App\Controller\TweetController::index

verTweet:
    path: /tweet/{id}
    controller: App\Controller\TweetController::verTweet

api_get_tweet:
    path: /api/tweets/{id}
    controller: App\Controller\ApiController::getTweet
    methods: ["GET"]

api_get_user:
    path: /api/users/{id}
    controller: App\Controller\ApiController::getTweetfonyUser
    methods: ["GET"]

api_get_tweets:
    path: /api/tweets
    controller: App\Controller\ApiController::getTweets
    methods: ["GET"]

api_get_users:
    path: /api/users
    controller: App\Controller\ApiController::getUsers
    methods: ["GET"]

api_index:
    path: /api
    controller: App\Controller\ApiController::index
    methods: ["GET","HEAD"]

api_post_user:
    path: /api/users
    controller: App\Controller\ApiController::postTweetfonyUser
    methods: ["POST"]

api_post_tweet:
    path: /api/tweets
    controller: App\Controller\ApiController::postTweet
    methods: ["POST"]

api_put_user:
    path: /api/users/{id}
    controller: App\Controller\ApiController::putTweetfonyUser
    methods: ["PUT"]

api_put_tweet:
    path: /api/tweet/{id}
    controller: App\Controller\ApiController::putTweet
    methods: ["PUT"]

api_delete_user:
    path: /api/user/{id}
    controller: App\Controller\ApiController::deteleTweetfonyUser
    methods: ["DELETE"]

api_delete_tweet:
    path: /api/tweet/{id}
    controller: App\Controller\ApiController::deleteTweet
    methods: ["DELETE"]

api_feedback:
    path: /api/users/{idUser}/tweets/{idTweet}
    controller: App\Controller\ApiController::feedback
    methods: ["PUT"]